import UserProvider  from './context/userProvider';
import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'
import Menu from './components/Menu';
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from 'react-toastify'



export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  
  return (
    <UserProvider>
    <html lang="en">
      <body>
        <Menu/>
        <ToastContainer position='top-center' />
      
       {children}

       <script src='https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js'></script>
      </body>
    </html>
    </UserProvider>
  );
}
